---

version: 0.2

env:
  parameter-store:
    JS30_CF_DISTR_ID: "/sandbox/metax7/js30/dev/JS30_CF_DISTR_ID"
    JS30_FULL_DOMAIN: "/sandbox/metax7/js30/dev/JS30_FULL_DOMAIN"
    JS30_ENV: "/sandbox/metax7/js30/dev/JS30_ENV"
    JS30_AUTH_HEADER: "/sandbox/metax7/js30/dev/JS30_AUTH_HEADER"
    JS30_API_GW_URL: "/sandbox/metax7/js30/dev/JS30_API_GW_URL"
    JS30_AUTH_TOKEN: "/sandbox/metax7/js30/dev/JS30_AUTH_TOKEN"
    JS30_APP_NAME: "/sandbox/metax7/js30/dev/JS30_APP_NAME"
    JS30_IDP_URL: "/sandbox/metax7/js30/dev/JS30_IDP_URL"
    JS30_AUTHORIZER_URL: "/sandbox/metax7/js30/dev/JS30_AUTHORIZER_URL"
    JS30_CACHE_CONTROL: "/sandbox/metax7/js30/dev/JS30_CACHE_CONTROL"

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 18
  pre_build:
    on-failure: ABORT
    commands:
      - echo installing npm dependencies
      - npm install
  build:
    on-failure: ABORT
    commands:
      - echo Build started on 'date'
      - npm run build
      - npm audit fix
      - echo "JS30_CF_DISTR_ID ${JS30_CF_DISTR_ID}"
      - echo "JS30_FULL_DOMAIN ${JS30_FULL_DOMAIN}"
      - echo "JS30_ENV ${JS30_ENV}"
      - echo "JS30_AUTH_HEADER ${JS30_AUTH_HEADER}"
      - echo "JS30_API_GW_URL ${JS30_API_GW_URL}"
      - echo "JS30_API_GW_URL ${JS30_AUTH_TOKEN}"
      - echo "JS30_APP_NAME ${JS30_APP_NAME}"
      - echo "JS30_IDP_URL ${JS30_IDP_URL}"
      - echo "JS30_AUTHORIZER_URL ${JS30_AUTHORIZER_URL}"
      - echo "JS30_CACHE_CONTROL ${JS30_CACHE_CONTROL}"
  post_build:
    on-failure: ABORT
    commands:
      - aws s3 cp --recursive ./dist s3://${JS30_FULL_DOMAIN}/ 
      - aws s3 cp --metadata-directive REPLACE --cache-control="${JS30_CACHE_CONTROL}" ./dist/index.html s3://${JS30_FULL_DOMAIN}/ 
  