version: 0.2

env:
  parameter-store:
    CF_DISTR_ID: "/sandbox/metax7/js30/CF_DISTR_ID"
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 18
  pre_build:
    on-failure: ABORT
    commands:
      - echo installing npm dependencies
      - npm install
  build:
    on-failure: ABORT
    commands:
      - echo Build started on 'date'
      - npm run build
      - npm audit fix
  post_build:
    on-failure: ABORT
    commands:
      - aws s3 cp --recursive ./dist s3://js30.metax7.my-best-code.com/
      - aws s3 cp --metadata-directive REPLACE --cache-control="max-age=60, s-maxage=86400" ./dist/index.html s3://js30.metax7.my-best-code.com/
      - aws cloudfront create-invalidation --distribution-id $CF_DISTR_ID --paths /*
  